# Generated by Django 6.0 on 2026-01-11 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyFuelReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateField()),
                ('fuel_consumed', models.CharField(max_length=50)),
                ('planned_quantity', models.CharField(max_length=40)),
                ('deliver_quantity', models.CharField(max_length=40)),
                ('remaining_quantity', models.CharField(max_length=40)),
                ('status', models.CharField(max_length=100)),
                ('craeted_at', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.user')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='location.site')),
            ],
        ),
    ]
