# Generated by Django 6.0 on 2026-01-11 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailyfuelreport',
            old_name='deliver_quantity',
            new_name='delivered_quantity',
        ),
    ]
